---
  mysqld_exporter_url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz
  mysqld_exporter: mysqld_exporter-0.12.1.linux-amd64.tar.gz
